  
name: 'Tests'

on:
  push:

  pull_request:
    types: [opened, synchronize] #labeled, assigned]

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            python-version: 3.9
            python: xvfb-run python3
            pip_arg: ""
          - os: macos-11
            python-version: 3.9
            python: python3
            pip_arg: ""
          - os: windows-2019
            python-version: 3.9
            python: python
            pip_arg: --user
          - os: ubuntu-22.04
            python-version: 3.11
            python: xvfb-run python3
            pip_arg: ""
    runs-on: ${{ matrix.os }}


    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ${{ matrix.pip_arg }} -e .

      - name: Python unittests
        run: |
          python -m unittest discover -v

      - name: Python plot
        run: |
          # Try to run main plot script
          python plot.py --noshow

      - name: Export figure
        run: |
          export CURRENT_HASH=`git rev-parse --short HEAD`
          echo "GITHUB_REF: $GITHUB_REF"
          if [[ $GITHUB_REF == *"main"* ]]; then 
             echo "Attemp to export generated figures"
             # Add the figures to the fig repository (only if the figures change)
             # TODO: do that with deploy or artifact insteady
             git checkout figs
             cp _figures_tmp/*.png figures/                        || true
             git add -f figures/*.png                              || true
             git commit -m "Update of figure after $CURRENT_HASH" || true
             git push --set-upstream origin figs
          fi
